---
- hosts: all
  become: yes
  roles:
    - common
    - repositories
    - php
    - httpd
    - useradd
    - mysql
    - wordpress
    - sshd
    - selinux
  vars_files:
    - group_vars/users.yml
