---
- name: install / Download WordPress
  git:
    repo: https://github.com/WordPress/WordPress.git
    dest: "/var/www/html/wordpress-{{ wordpress_version }}"
    version: "{{ wordpress_version }}-branch"

- name: install / Link wordpress root document
  file:
    src: /var/www/html/wordpress-{{ wordpress_version }}
    path: /var/www/html/wordpress
    owner: apache
    group: apache
    state: link

- name: install / Change ownership in WordPress
  file:
    path: /var/www/html/wordpress-{{ wordpress_version }}
    owner: apache
    group: apache
    recurse: yes

