---
- name: remove mariadb-libs
  dnf:
    state: absent
    name: mariadb-libs

- name: install mysql server
  dnf:
    state: latest
    name:
      - mysql-server
      - python3-PyMySQL
      - mysql
#
