---
- name: check java installed
    shell: which java
      register: java_which
        failed_when: java_which.rc not in [0, 1]
         
- name: install java
    yum: name=java-{{ java_version }}-openjdk
      when: java_which.rc == 1
