---
- name: yum update
  yum: name=* state=latest

- name: install list of packages
  yum:
    name: "{{ item }}"
  loop:
    - vim
    - wget
    - git
    - bind-utils
    - chrony

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: start NTP service
  service:
    name: chronyd
    state: restarted

- name: set hostname
  become: true
  hostname:
    name: "{{ hostname }}"

- name: set root password
  user:
    name: root
    password: "{{ '<password>'|password_hash('sha512') }}"
