---
- name: yum or dnf update
  yum: name=* state=latest

- name: install list of packages
  yum:
    name: "{{ item }}"
  loop:
    - vim
    - wget
    - git
    - bind-utils
    - chrony

- name: start NTP service
  service:
    name: chronyd
    state: restarted