---
- name: dnf moduleinstall
  shell: "dnf module reset -y php;dnf module install -y php:remi-{{ php_version }}"

- name: enable powertools
  shell: 'dnf config-manager --set-enabled PowerTools'

- name: php module install
  yum:
    name: "{{ item }}"
    enablerepo: remi
  loop: "{{ php_modules }}"
