---
- name: CentOS6 start httpd
  service:
    name: httpd
    state: restarted
  when:
    - ansible_distribution in ['CentOS','RedHat']
    - ansible_distribution_major_version == "6"

- name: CentOS7 or 8 start httpd
  systemd:
    name: httpd
    state: restarted
  when:
    - ansible_distribution in ['CentOS','RedHat']
    - ansible_distribution_major_version in ["7", "8"]

